name: CI/CD with Postman Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Step 3: Install Newman
      - name: Install dependencies
        run: npm install -g newman  # Install Newman globally

      # Step 4: Run Postman tests directly with URL
      - name: Run Postman tests
        run: |
          newman run Software_test.postman_collection.json -e https://node-deploy-group-9.onrender.com/api/env/postman_environment.json || \
          newman run Software_test.postman_collection.json -r cli,html
          --reporter-html-export newman-report.html

      # Step 5: Upload Newman HTML Report as an artifact
      - name: Upload Newman HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
