name: CI/CD with Postman Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Step 3: Install Newman
      - name: Install Newman
        run: |
          npm install -g newman  # Install Newman globally

      # Step 4: Run Postman tests using CLI only
      - name: Run Postman tests
        run: |
          newman run Software_test.postman_collection.json --reporters cli

      # Step 5: Upload CLI Report as artifact (if needed)
      - name: Upload CLI Report as Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: newman-cli-report
          path: newman-report.json  # This will save any CLI output, like test results
